# This workflow will checkout a repo for building schema to typescript,
# then fetch the latest schema from pretext, and build it.  It will then create a PR for the change (if there are any).

name: Update Schema
on:
  schedule:
    - cron: '0 0 * * 0' # every Sunday at midnight
  workflow_dispatch:

jobs:
  update-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: generate new schema
        run: |
          git clone https://github.com/siefkenj/relax-ng-to-typescript.git
          cd relax-ng-to-typescript
          npm install
          wget https://raw.githubusercontent.com/PreTeXtBook/pretext/refs/heads/master/schema/pretext.rng
          npx vite-node scripts/generate-typescript.ts -- -g pretext.rng -o ./
          cp -f ./generated-grammar.ts ../packages/jsx/src/assets/generated-grammar.ts
          cp -f ./generated-types.ts ../packages/jsx/src/assets/generated-types.ts
          cd ..
          rm -rf relax-ng-to-typescript

      - name: setup git config
        run: |
          git config user.name "${{ github.actor }} via GitHub Actions"
          git config user.email "${{ github.actor }}@github_actions.no_reply"

      - name: check for changes
        run: |
          git checkout -b schema-update-action
          git diff --quiet || {
            git add .
            git commit -m "Update relaxng schema"
            git push --set-upstream origin schema-update-action
            gh pr create --fill
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
